### ISSUE TITLE
MPII & AIchallenge

### ISSUE THREAD

**Issue by SuperJay1996** [DeepInsight-PCALab/Dataset-Catalog-#1]
Dataset Name:MPII
Path:/data3/MPII
Size:24G
Home Page: http://human-pose.mpi-inf.mpg.de/
Keywords:2D pose estimation
Miscellaneous: Including images,processed masks and keypoints anntations
Applicant: XuJie

Dataset Name: AIchallenge
Path: /data3/AIchallenge
Size: 29G
Home Page: https://challenger.ai/competition/keypoint/subject
Keywords: 2D multi-person pose estimation
Miscellaneous: The dataset of AIchallenge for human pose estimation,including images,bboxes and keypoints annotations
Applicant:XuJie

**Comment by dichen-cd** [comment]
两者的实际大小出入有点大，MPII 实际占用大小大概在 135.6G, AIchallenge 实际占用大小大概为 3.7T . 看一下是不是平时产生的中间结果都放在里边了，能删除的尽量删除，尽可能保持数据集干净。

**Comment by SuperJay1996** [comment]
额，这是我昨天删除后du的结果，我删了好多




发自网易邮箱 iPhone 版
在2018年03月07日 09:56，陈狄 写道：

两者的实际大小出入有点大，MPII 实际占用大小大概在 135.6G, AIchallenge 实际占用大小大概为 3.7T . 看一下是不是平时产生的中间结果都放在里边了，能删除的尽量删除，尽可能保持数据集干净。

**Comment by dichen-cd** [comment]
OK
