### ISSUE TITLE
KAIST_Infrared_Pedestrain

### ISSUE THREAD

**Issue by csjfwang** [DeepInsight-PCALab/Dataset-Catalog-#11]
Dataset Name:  KAIST_Infrared_Pedestrain
Path:  /data3/KAIST_Infrared_Pedestrain
Size:  36G
Homepage:  https://sites.google.com/site/pedestrianbenchmark/
Keywords:  Pedestrian detection
Miscellaneous：Including RGB images, infrared images, and labeled bounding box.

jifeng

**Comment by dichen-cd** [comment]
OK.
