### ISSUE TITLE
RESIDE

### ISSUE THREAD

**Issue by csjfwang** [DeepInsight-PCALab/Dataset-Catalog-#12]
Dataset Name: RESIDE
Path: /data3/RESIDE
Size: 98G (Origin .zip files)
Homepage: https://sites.google.com/view/reside-dehaze-datasets
Keywords: Dehazing/ haze removal
Miscellaneous：Including RGB pairs(haze & clean), gray scale images(transmission maps).

jifeng

**Comment by dichen-cd** [comment]
OK.
