### ISSUE TITLE
pku_Rain

### ISSUE THREAD

**Issue by csjfwang** [DeepInsight-PCALab/Dataset-Catalog-#13]
Dataset Name: pku_Rain
Path: /data3/pku_Rain/rainALL_ALL
Size: 8.6G
Homepage: http://www.icst.pku.edu.cn/struct/Projects/joint_rain_removal.html?jekfcbimoppphdba
Keywords: Deraining/ rain removal
Miscellaneous：Including RGB pairs(rain & clean), labeled rain steaks.

jifeng

**Comment by dichen-cd** [comment]
OK.
