### ISSUE TITLE
Snow100K

### ISSUE THREAD

**Issue by csjfwang** [DeepInsight-PCALab/Dataset-Catalog-#14]
Dataset Name: Snow100K
Path: /data3/Snow
Size: 16G (origin .zip files)
Homepage: https://sites.google.com/view/yunfuliu/desnownet
Keywords: desnow/ snow removal
Miscellaneous：Including RGB pairs(snow & clean), labeled snow locations.

jifeng

**Comment by dichen-cd** [comment]
OK.
