### ISSUE TITLE
Datasets provided by Chuanwei

### ISSUE THREAD

**Issue by deepcharle** [DeepInsight-PCALab/Dataset-Catalog-#15]
Provided by ChuanweiZhou
Dataset: FlyingChairs  path:/data3/FlyingChairs/FlyingChairs  size: 1.1T
keywords: optical flow estimation
homepage: https://lmb.informatik.uni-freiburg.de/resources/datasets/FlyingChairs.en.html
description: including training and testing data along with those transformed into tensorflow tfrecords files

Dataset: FlyingThings  path:/data3/FlyingThings  size: 1.3T
keywords: optical flow estimation
homepage: https://lmb.informatik.uni-freiburg.de/resources/datasets/SceneFlowDatasets.en.html
description: including training and testing data along with those transformed into tensorflow tfrecords files, where optical flow was only transformed from left view as well as in the order of into_future

dataset: MPI-Sintel  path: /data3/MPI_Sintel size: 12G
keywords: optical flow estimation
homepage: http://sintel.is.tue.mpg.de/
description: including all training and testing data of MPI-Sintel dataset, especially for evaluating the performance of optical flow algorithms

Dataset: MOT path:/data3/MOT size: 1.9G
keywords： multi object tracking
homepage: https://motchallenge.net/
description: including training and testing data of mot dataset for multi object tracking, also including optical flow extracted by flownet2.0 if any help for tracking

dataset: vot path: /data3/VOT/vot2015  size: 1.4G
keywords: single object tracking
homepage: http://www.votchallenge.net/
description: including training and testing data of vot dataset for single object tracking, also including optical flow extracted by flownet2.0 if any help for tracking

dataset: Charades path: /data3/Charades  size: 396G
keywords: video recognition & video caption
homepage: http://allenai.org/plato/charades/
description: including videos, flows of original size as well as those scaled into 480p, along with two-stream features computed by frames and optical flows in the frequency of 8fps. Evaluation codes were also provided

dataset: VID_detec  path:/data3/Imagenet/ILSVRC2017/ size: 359G
keywords: video detection
homepage: http://www.image-net.org/challenges/LSVRC/
description: including all data from the Imagenet 2017 Challenge for video object detection, composed of DET and VID subsets.

**Comment by dichen-cd** [comment]
数据集的大小呢？

**Comment by dichen-cd** [comment]
`FlyingChairs`, `FlyingThings `, `MPI-Sintel` 三者关系混乱。如果是三个不同的数据集就请分开放置。并且后两者的数据集大小缺失。

`out_flow ` 数据集缺少来源。

`VID_detec` 请归类到 `/data3/ImageNet` 目录下，并标明是17年的数据。如果跟`ILSVRC2010`, `ILSVRC2012`, `ILSVRC2015` 有重合的话请删除重复部分。

**Comment by dichen-cd** [comment]
OK. 写的很详细。
