### ISSUE TITLE
data

### ISSUE THREAD

**Issue by destinyzs** [DeepInsight-PCALab/Dataset-Catalog-#2]
Name: Kitti
Path: /data3/Kitti
Size: 357GB
Home Page:http: //www.cvlibs.net/datasets/kitti/
Keywords: Autonomous Driving
Miscellaneous: including stereo and optical flow image pairs, stereo visual odometry sequences, and 3D object annotations
Li Chengzheng

**Comment by dichen-cd** [comment]
OK.
