### ISSUE TITLE
QIAO-DATASET

### ISSUE THREAD

**Issue by Qiaoxinshu** [DeepInsight-PCALab/Dataset-Catalog-#20]
Dataset Name: CIFAR100
Path: /data3/cifar10
Size: 939M
Homepage: http://www.cs.toronto.edu/~kriz/cifar.html
---------------------------------------------------------------------------------------------------------------
Dataset Name: SVHN
Path: /data3/SVHN
Size: 2.5G
Homepage: http://ufldl.stanford.edu/housenumbers/
---------------------------------------------------------------------------------------------------------------
Dataset Name: HMDB-51
Path1: /data3/hmdb51  %备注：原始视频文件
Size: 2.1G
Path2: /data3/hmdb51_flow  %备注：视频帧光流图
Size: 25G
Path3: /data3/hmdb51_frame  %备注：视频帧
Size: 17G
Path4: /data3/IDTfeature  %备注：视频数据的IDT特征，以后可能还要用，可以留着么
Size: 302G
Homepage: http://serre-lab.clps.brown.edu/resource/hmdb-a-large-human-motion-database/
---------------------------------------------------------------------------------------------------------------
Dataset Name: UCF-101
Path1: /data3/UCF-101  %备注：原始视频文件
Size: 6.8G
Path1: /data3/ucf_frame %备注：视频帧
Size: 63G
Path1: /data3/ucf_transed %备注：视频帧光流图
Size: 94G
Homepage: http://crcv.ucf.edu/data/UCF101.php
---------------------------------------------------------------------------------------------------------------
Dataset Name: Youtube-8M
Path: /data3/Youtube-8M
Size: 1.8T
Homepage: https://research.google.com/youtube8m/
---------------------------------------------------------------------------------------------------------------

**Comment by dichen-cd** [comment]
`/data3/hmdb51_flow` 和 `/data3/hmdb51_frame` 是怎么回事？

**Comment by Qiaoxinshu** [comment]
等下哈，我还没弄好
