### ISSUE TITLE
Datasets for traffic signal detection

### ISSUE THREAD

**Issue by insmod-he** [DeepInsight-PCALab/Dataset-Catalog-#22]
**Dataset Name**: Tsinghua-Tencent 100K
**Path**: /data3/Tsinghua_Tencent_100K
**Size**: 24.5G
**Homepage**: http://cg.cs.tsinghua.edu.cn/traffic-sign/tutorial.html 

**Dataset Name**: 2017年中国智能车未来挑战赛数据
**Path**: /data3/XJTU2017
**Size**: 26G
**Homepage**: http://ccvai.xjtu.edu.cn/jjy.jsp?urltype=tree.TreeTempUrl&wbtreeid=1003

**Dataset Name**: Traffic Light Datasets
**Path**: /data3/TrafficLight
**Size**: 36G
**Homepage**: https://github.com/udacity/self-driving-car/tree/master/annotations， https://hci.iwr.uni-heidelberg.de/node/6132

Hongliang

**Comment by dichen-cd** [comment]
OK
