### ISSUE TITLE
vot datasets

### ISSUE THREAD

**Issue by Cris-zj** [DeepInsight-PCALab/Dataset-Catalog-#23]
datasetname: vot2014
path: /data3/VOT/vot2014
size: 454M
homepage: http://www.votchallenge.net/vot2014/
keywords: single object tracking
Miscellaneous: Including annotations and images
applicant: zhujiao_4047

datasetname: vot2015
path: /data3/VOT/vot2015
size: 1.4G
homepage: http://www.votchallenge.net/vot2015/
keywords: single object tracking
Miscellaneous: Including annotations and images
applicant: zhujiao_4047

**Comment by dichen-cd** [comment]
Done.
