### ISSUE TITLE
Grasping Rectangle Dataset

### ISSUE THREAD

**Issue by sparkydogX** [DeepInsight-PCALab/Dataset-Catalog-#24]
Dataset Name: GraspingRectangleDataset
Path: /data3/GraspingRectangle/
Size: 10G
Home Page: http://pr.cs.cornell.edu/deepgrasping/
Keywords: RGBD detection
Miscellaneous: A dataset for detecting robotic grasps
Applicant:Guoyu

**Comment by dichen-cd** [comment]
OK.
