### ISSUE TITLE
Human 3.6M

### ISSUE THREAD

**Issue by sparkydogX** [DeepInsight-PCALab/Dataset-Catalog-#25]
Dataset Name: Human 3.6M
Path: /data3/Human36M
Size: 32G
Home Page: http://vision.imar.ro/human3.6m/description.php
Keywords: RGBD Human Pose Estimation
Miscellaneous: A dataset for detecting human keypoints from RGBD data
Applicant:Guoyu

**Comment by dichen-cd** [comment]
Done.
