### ISSUE TITLE
Visual Genome

### ISSUE THREAD

**Issue by destinyzs** [DeepInsight-PCALab/Dataset-Catalog-#26]
Dataset Name: Visual Genome
Path: /data3/Visual_Genome
Size: 15G
Home Page: http://visualgenome.org/
Keywords: Visual Relationship Detection
Miscellaneous: Visual Genome is a dataset, a knowledge base, an ongoing effort to connect structured image concepts to language.
Applicant:LiChengZheng

**Comment by dichen-cd** [comment]
Done.
