### ISSUE TITLE
KITTI 2018 Depth

### ISSUE THREAD

**Issue by JesseZhang92** [DeepInsight-PCALab/Dataset-Catalog-#27]
path: data3/KITTI_2018_depth

size: 100~200GB

website: http://www.cvlibs.net/datasets/kitti/eval_depth_all.php

**Comment by dichen-cd** [comment]
KITTI_2018_depth 跟已有的 `/data3/Kitti` 有什么关系？ 是否有重复？两者至少是从属的关系，请将`data3/KITTI_2018_depth` 整理后并入 `/data3/Kitti`.

**Comment by dichen-cd** [comment]
Done.
