### ISSUE TITLE
MOT2017

### ISSUE THREAD

**Issue by 2a2a** [DeepInsight-PCALab/Dataset-Catalog-#28]
Dataset Name: MOT2017
Path: /data3/MOT/MOT2017
Size:5.5G
Home Page: https://motchallenge.net/data/MOT17/#download
Keywords:  Multiple Object Tracking
Miscellaneous: MOT17 Challenge. All MOT16 sequences are used with a new, more accurate ground truth. Each sequences is provided with 3 sets of detections: DPM, Faster-RCNN, and SDP.
Applicant: Wangyufan

**Comment by dichen-cd** [comment]
Done.
