### ISSUE TITLE
DIDI 2nd self-driving competition

### ISSUE THREAD

**Issue by swordlidev** [DeepInsight-PCALab/Dataset-Catalog-#29]
（1）数据集名称
滴滴第二届无人驾驶比赛数据集
（2）下载路径
http://research.xiaojukeji.com/
（3）预计大小
500G
（4）官方主页
http://research.xiaojukeji.com/
（5）关键词（数据集用于什么任务/实验）
多传感器数据进行三维目标检测

**Comment by dichen-cd** [comment]
Done.
