### ISSUE TITLE
COCO dataset

### ISSUE THREAD

**Issue by sparkydogX** [DeepInsight-PCALab/Dataset-Catalog-#3]
Dataset Name: COCO
Path: /data3/MSCOCO
Size: 140G
Home Page: http://cocodataset.org/#home
Keywords: detection, pose estimation,segmentation
Miscellaneous:COCO is a large-scale object detection, segmentation, and captioning dataset. 
Applicant:Guoyu

**Comment by dichen-cd** [comment]
Done.
