### ISSUE TITLE
DOTA

### ISSUE THREAD

**Issue by destinyzs** [DeepInsight-PCALab/Dataset-Catalog-#30]
Dataset Name: DOTA
Path: /data3/DOTA
Size: 20G
Home Page: http://captain.whu.edu.cn/DOTAweb/
Keywords: Aerial Images
Miscellaneous: A Large-scale Dataset for Object Detection in Aerial Images
Applicant: LiChengZheng

**Comment by dichen-cd** [comment]
只是好奇一下，CVPR2018出的数据集，你们这么快就跟进了用上了吗？？

**Comment by destinyzs** [comment]
额，我正在做小目标检测方面的工作，于是就发现了这个神奇的数据集…

**Comment by Angzz** [comment]
awesome dataset!!!

**Comment by dichen-cd** [comment]
好的。顺便可以关注一下人脸检测的工作，比如 TinyFace 这样的，也是小目标检测。

**Comment by destinyzs** [comment]
好的，谢谢师兄。
