### ISSUE TITLE
COCO_keypoint_2014

### ISSUE THREAD

**Issue by ktr-hubrt** [DeepInsight-PCALab/Dataset-Catalog-#32]
Name: coco_keypoint_2014
Path: /data3/MSCOCO/fmap & /data3/MSCOCO/Fmap
Size: 65.4G
Home Page: http://cocodataset.org/#download
Keywords: keypoint_featuremap
Miscellaneous: including mats and npy
Hui Lv

**Comment by dichen-cd** [comment]
这是你在原有数据集上跑模型得到的keypoint featuremap吧？是的话在`/data3/MSCOCO` 这个目录下写一个说明文档 `README_fmap_Fmap.md`

**Comment by ktr-hubrt** [comment]
ok

**Comment by ktr-hubrt** [comment]
on the web or the dataset?
