### ISSUE TITLE
ILSVRC2015 & ALOV

### ISSUE THREAD

**Issue by Cris-zj** [DeepInsight-PCALab/Dataset-Catalog-#4]
Dataset Name: ILSVRC2015
Path: /data3/ImageNet/ILSVRC2015
Size: 179G
Home Page: http://www.image-net.org/
Keywords: Object Detection/Object Tracking
Miscellaneous: Including competitions: Object detection and Object detection from video (VID), because they have the same folder name for different tasks, so you can search the files to find that you want.
applicant: zhujiao_4047

Dataset Name: ALOV
Path: /data3/alov
Size: 11G
Home Page: http://alov300pp.joomlafree.it/
Keywords: Object Tracking
Miscellaneous: Including annotations and images
applicant: zhujiao_4047

**Comment by dichen-cd** [comment]
描述得再精确一些。

ILSVRC2014 是一个综合性竞赛，包含了各种任务。请注明跟任务直接相关的主页，并且在路径名中注明这是用作检测和跟踪的子集。否则容易被其他人误认为是 ImageNet 物体分类的数据。

**Comment by Cris-zj** [comment]
师兄，ILSVRC2014的这个数据集是用来训练trakcer的，它那年是没有video的比赛，那我该怎么定义这个数据集？

**Comment by DeanChan** [comment]
ILSVRC2014 有Dataset1和

**Comment by dichen-cd** [comment]
[ILSVRC2014](http://www.image-net.org/challenges/LSVRC/2014/) 分为 Dataset 1: Detection 和 Dataset 2: Classification and localization. 你需要说清楚 /data3/ImageNet/ILSVRC2014 这个文件夹下现有的数据是啥。同样对于 [ILSVRC2015](http://image-net.org/challenges/LSVRC/2015/) 也是。

除此之外，ILSVRC2015 中是不是与 ILSVRC2014 有大量的重复数据？如果有的话最好表明并删除重复数据。

**Comment by dichen-cd** [comment]
Resolved.
