### ISSUE TITLE
UCF_Crime

### ISSUE THREAD

**Issue by deepcharle** [DeepInsight-PCALab/Dataset-Catalog-#40]
location: /data3/UCF_Crime
homepage: http://crcv.ucf.edu/projects/real-world/
size: unknown till now, will update later
description: a dataset for anomaly detection, including initial video, generated images and optical flows

**Comment by dichen-cd** [comment]
Noted. Be sure to update the dataset size later.

**Comment by deepcharle** [comment]
the dataset size is about 208GB

**Comment by dichen-cd** [comment]
Done.
