### ISSUE TITLE
Super resolution dataset

### ISSUE THREAD

**Issue by opteroncx** [DeepInsight-PCALab/Dataset-Catalog-#41]
location: data3/Super_resolution
Dataset: NTIRE18 (DIV2K), Train391(Y91+bsd200+general100), Testing datasets for super resolution (bsd100,set5,set14,Manga109 etc.)
Totalsize: ~200G
web: https://data.vision.ee.ethz.ch/cvl/DIV2K/
description: dataset for single image super resolution tasks
ChengXi_3058

**Comment by dichen-cd** [comment]
Do not merge different datasets into a single path. Split them into `/data3/DIV2K` `/data3/Y91`, etc.
