### ISSUE TITLE
CUB-200-2011 and Online Product Datasets

### ISSUE THREAD

**Issue by ZRStea** [DeepInsight-PCALab/Dataset-Catalog-#42]
Datasets:
CUB-200-2011
http://www.vision.caltech.edu/visipedia/CUB-200-2011.html  1.1GB

Online Product
http://cvgl.stanford.edu/projects/lifted_struct/  2.9G

Two datasets are for birds classification and products retrieval. Both are widely used in metric learning field.

**Comment by dichen-cd** [comment]
路径？

**Comment by ZRStea** [comment]
/data3 is ok, I prefer /data4, because It will have much reading requirement like Market1501

**Comment by dichen-cd** [comment]
Is it `/data3/CUB-200-2011` and `/data3/OnlineProduct` or `/data3/Online_Product` or `/data3/Online-Product` ?

**Comment by ZRStea** [comment]
Underline style, please

**Comment by dichen-cd** [comment]
`/data3/CUB-200-2011` or `/data3/CUB_200_2011`?

**Comment by ZRStea** [comment]
`/data3/CUB_200_2011` and `/data3/Online_Product`

**Comment by dichen-cd** [comment]
Done.
