### ISSUE TITLE
Automated Driving 3D Point Cloud Segmentation

### ISSUE THREAD

**Issue by fangyuan123** [DeepInsight-PCALab/Dataset-Catalog-#44]
Location: data3/3D Point Cloud Segmentation
DataSet: Automated Driving 3D Point Cloud Segmentation
Totalsize: about 86.5G
Web: https://www.datafountain.cn/competitions/314/details/data-evaluation?tdsourcetag=s_pctim_aiomsg
Description: dataset for automated driving 3D point cloud segmentation
FangYuan-4047

**Comment by dichen-cd** [comment]
Avoid spaces in path name. Would `/data3/3D_Point_Cloud_Segmentation` be okay?

**Comment by dichen-cd** [comment]
Avoid spaces in path name. Would `/data3/3D_Point_Cloud_Segmentation` be okay?

**Comment by fangyuan123** [comment]
OK!Thanks!

**Comment by dichen-cd** [comment]
Done.
