### ISSUE TITLE
TrackingNet dataset

### ISSUE THREAD

**Issue by Cris-zj** [DeepInsight-PCALab/Dataset-Catalog-#45]
datasetname: TrackingNet
path:/data3/TrackingNet/
size: downloading
homepage: https://tracking-net.org/
Miscellaneous: including images and labels
applicant: zhujiao_4047

the dataset is very large, so I should make an application first in case that the administrator delete it.

**Comment by dichen-cd** [comment]
Remember to update the size in this issue.

**Comment by Cris-zj** [comment]
OK
