### ISSUE TITLE
Add new elements to current Kitti dataset

### ISSUE THREAD

**Issue by deepcharle** [DeepInsight-PCALab/Dataset-Catalog-#46]
I need to add some new subset of Kitti dataset to the current Kitti dataset in /data3/Kitti for the task of 3D object detection. main page: http://www.cvlibs.net/datasets/kitti/eval_object.php?obj_benchmark=3d.
the new added subset will be about 72 GB.

**Comment by dichen-cd** [comment]
Noted.
