### ISSUE TITLE
apply for dataset

### ISSUE THREAD

**Issue by wuweialways17** [DeepInsight-PCALab/Dataset-Catalog-#48]
dataset_name: ai_challenger_caption
path:/data3/ai_challenger_caption
size: 21.7GB
content: images and captions（both for training and validating)
applicant: 4056 wuwei
explain: it has been downloaded to my personal computer, and i want to ask for permit to upload it to data3 for our research, which is about "image caption in Chinese".

**Comment by dichen-cd** [comment]
Please add the homepage for this dataset. Gonna verify the data source.

**Comment by wuweialways17** [comment]
cause It is an open dateset for ai-challenger2017，and its homepage has been replaced by ai-challenger2018, which means it cant be downloaded from an official website. However, you can search it to verify its authenticity.  Im sorry for this issue.

发送自 Windows 10 版邮件应用

发件人: 陈狄
发送时间: 06 November 2018 09:47
收件人: DeepInsight-PCALab/Dataset-Catalog-
抄送: wuwei; Author
主题: Re: [DeepInsight-PCALab/Dataset-Catalog-] apply for dataset (#48)

Please add the homepage for this dataset. Gonna verify the data source.

**Comment by dichen-cd** [comment]
Done.
