### ISSUE TITLE
XJTU2017 + DeepInsight 

### ISSUE THREAD

**Issue by implus** [DeepInsight-PCALab/Dataset-Catalog-#5]
XJTU2017  |  /data3/XJTU2017 |  25.9G | http://ccvai.xjtu.edu.cn/qxkz/yhdl.jsp?urltype=tree.TreeTempUrl&wbtreeid=1035&wbnewsid=1300 |   5 tasks related to self-driving system (1. traffic line detection 2. traffic sign detection 3. vehicle detection 4. lane keeping monitoring 5. vehicle distance estimation) | Including Images, traffic lines, traffic sign bboxes and types, vehicle bboxes,  vehicle distances
 
DeepInsight | /data3/DeepInsight | 296G | no website | self-constructed dataset for traffic line detection (under development) |  Including images, hand-labeled traffic lines (still going on), some codes for processing images and labels, several pre-trained models

**Comment by DeanChan** [comment]
Done.
