### ISSUE TITLE
SBU & ISTD Dataset

### ISSUE THREAD

**Issue by csjfwang** [DeepInsight-PCALab/Dataset-Catalog-#58]
Dataset Name: SBU and ISTD (Two shadow dataset).
Path: /data3/shadow
Size: 10G (Total). SBU: 7.8G, ISTD: 1.4G.
Homepage: 
SBU: https://www3.cs.stonybrook.edu/~minhhoai/projects/shadow.html
ISTD: https://github.com/DeepInsight-PCALab/ST-CGAN

Keywords: DeShadow/ shadow detection/ shadow removal
Miscellaneous：Including RGB pairs, RGB triplets.

jifeng

**Comment by dichen-cd** [comment]
Done.
