### ISSUE TITLE
AVOD_Kitti

### ISSUE THREAD

**Issue by fangyuan123** [DeepInsight-PCALab/Dataset-Catalog-#59]
Dataset Name: kitti 3d object detection dataset
Path: /data3/AVOD_Kitti
Size: 73.2G
Homepage: http://www.cvlibs.net/datasets/kitti/eval_object.php?obj_benchmark=3d
Keywords: 3d object detection dataset, velodyne, images

fangyuan4047

**Comment by dichen-cd** [comment]
What's the relationship between AVOD_Kitti and Kitti?

If it's a subset, be sure to merge into the Kitti dataset, instead of creating a new on2.

**Comment by fangyuan123** [comment]
Ok! Thanks!
