### ISSUE TITLE
DAVIS16

### ISSUE THREAD

**Issue by JesseZhang92** [DeepInsight-PCALab/Dataset-Catalog-#6]
Dataset Name: DAVIS16

Path: data3/DAVIS-data-origin

Size: 7.20G

Homepage: http://davischallenge.org/code.html

**Comment by dichen-cd** [comment]
诶？路径应该是 `/data3/DAVIS16` 还是 `/data3/DAVIS-data-origin` ???

**Comment by JesseZhang92** [comment]
是后面那个，前面那个似乎被污染了。

**Comment by dichen-cd** [comment]
OK.
