### ISSUE TITLE
Scene Flow dataset

### ISSUE THREAD

**Issue by JesseZhang92** [DeepInsight-PCALab/Dataset-Catalog-#60]
path: data3/SceneFlow
size: 15.1GB
official website: https://lmb.informatik.unifreiburg.de/resources/datasets/SceneFlowDatasets.en.html

a popular synthetic dataset for disparity, optical flow estimation.

**Comment by dichen-cd** [comment]
Looks like the website is invalid. @JesseZhang92

**Comment by JesseZhang92** [comment]
https://lmb.informatik.uni-freiburg.de/resources/datasets/SceneFlowDatasets.en.html
try this

**Comment by dichen-cd** [comment]
Done.
