### ISSUE TITLE
data3/ILSVRC2017_DET

### ISSUE THREAD

**Issue by dexinR** [DeepInsight-PCALab/Dataset-Catalog-#66]
datasetname: ILSVRC2017_DET
path:/data3/ILSVRC2017_DET/
size: 56.7GB for ILSVRC2017_DET.tar.gz. and 428MB for ILSVRC2017_DET_test_new.tar.gz. Not sure how large it will be after unzipped.
homepage: http://image-net.org/download
Miscellaneous: images, labels, bounding box 
applicant: Dexin Ren

The dataset is in use for Weakly Supervised Learning for Real-World Computer Vision Applications and the 1st Learning from Imperfect Data (LID) Challenge. And it can be commonly use for object detection. 
ILSVRC2017_DET_test_new.tar.gz:The dataset is unchanged from ILSVRC2016. There are a total of 456567 images for training. The number of positive images for each synset (category) ranges from 461 to 67513. The number of negative images ranges from 42945 to 70626 per synset. There are 20121 validation images and 60000 test images. All images are in JPEG format.
ILSVRC2017_DET.tar.gz:The file only contains 5500 new images and the test.txt file.

**Comment by dexinR** [comment]
the real size will be updated after the zip file get download and unzipped. And the zip file will also be deleted after that.

**Comment by Cris-zj** [comment]
ILSVRC2017_DET dataset has been in the dir /data3/ImageNet/ILSVRC2017. Please confirm it and remove the dir data3\ILSVRC2017_DET you build to release the memory

**Comment by dichen-cd** [comment]
Many thanks to @Cris-zj

**Comment by dexinR** [comment]
OK，deleted
