### ISSUE TITLE
GTOT dataset

### ISSUE THREAD

**Issue by chaoqunwangcs** [DeepInsight-PCALab/Dataset-Catalog-#68]
dataset name:GTOT
path: data3/GTOT
size: 1.6G
homepage: http://hcp.sysu.edu.cn/resources/
Miscellaneous: images, labels
applicant: Wang Chaoqun_4047

**Comment by dichen-cd** [comment]
Looks like the homepage is invalid.

Could you update the link?

**Comment by chaoqunwangcs** [comment]
> Looks like the homepage is invalid.
> 
> Could you update the link?

the link in the paper is invalid, I got the dataset from the author's homepage http://chenglongli.cn, 
it’s just a google cloud drive link, https://docs.google.com/uc?id=0B-Z6TyBF2ceIZ0c1anVhaHQ3MFk&export=download,

**Comment by dichen-cd** [comment]
Done.

**Comment by Kababey** [comment]
> > Looks like the homepage is invalid.
> > Could you update the link?
> 
> the link in the paper is invalid, I got the dataset from the author's homepage http://chenglongli.cn, it’s just a google cloud drive link, https://docs.google.com/uc?id=0B-Z6TyBF2ceIZ0c1anVhaHQ3MFk&export=download,

Drive link is broken, is there any available source?
