### ISSUE TITLE
PARD dataset

### ISSUE THREAD

**Issue by sparkydogX** [DeepInsight-PCALab/Dataset-Catalog-#69]
Dataset Name: PARD (Pedestrian action recognition dataset)
Path:/data3/PARD
Size:29G
Keywords: Pedestrian action recognition dataset
Miscellaneous: Including video clips and corresponding heatmap.
Applicant: Yu Guo

**Comment by dichen-cd** [comment]
Website?

**Comment by sparkydogX** [comment]
> Website?

We propose this dataset and it is not publicly accessible yet. Thus the website doesn't exist.

**Comment by dichen-cd** [comment]
Cool.

**Comment by dichen-cd** [comment]
Done.
