### ISSUE TITLE
DAVIS 17

### ISSUE THREAD

**Issue by JesseZhang92** [DeepInsight-PCALab/Dataset-Catalog-#7]
Dataset Name: DAVIS 17

Path: data3/DAVIS17

Size: 12GB

Homepage: http://davischallenge.org/code.html

**Comment by dichen-cd** [comment]
/data3 下有四个 DAVIS 相关的文件夹 `DAVIS16`, `DAVIS17`, `DAVIS-data`, `DAVIS-data-origin`. 这几个文件夹的关系理一理。 #6

**Comment by JesseZhang92** [comment]
是的，除去我在ISSUE里写到的两个，其他两个是他人上传且重复的数据。

**Comment by dichen-cd** [comment]
OK. `DAVIS-data`以及`DAVIS-data-origin` 将被删除。
