### ISSUE TITLE
add ECP dataset

### ISSUE THREAD

**Issue by dmy1997** [DeepInsight-PCALab/Dataset-Catalog-#72]
name: the ECP dataset(EuroCity Persons Dataset)
download path: data3/ECP
size: 100GB(compression condition)
home page: https://eurocity-dataset.tudelft.nl/eval/benchmarks/detection
application: pedestrain detection
description: The ECP dataset. Focus on Persons in Urban Traffic Scenes.
With over 238200 person instances manually labeled in over 47300 images, EuroCity Persons is nearly one order of magnitude larger than person datasets used previously for benchmarking. Diversity is gained by recording this dataset throughout Europe.

**Comment by dichen-cd** [comment]
Done.
