### ISSUE TITLE
NightOwls: A Pedestrians at Night Dataset

### ISSUE THREAD

**Issue by ligang-cs** [DeepInsight-PCALab/Dataset-Catalog-#73]
dataset: NightOwls
path: /data3/NightOwls
size: 185G(zip file)
homepage: http://www.nightowls-dataset.org/download/
description: A pedestrians at night dataset
miscellaneous: including training and validation images(image resolusion 1024x640)
applicant: LIGang

**Comment by dichen-cd** [comment]
Done.
