### ISSUE TITLE
NYU depth

### ISSUE THREAD

**Issue by JesseZhang92** [DeepInsight-PCALab/Dataset-Catalog-#8]
Dataset Name: NYU depth v2

Path: data3/NYU_depth

Size: 428G

Homepage: https://cs.nyu.edu/~silberman/datasets/nyu_depth_v2.html

**Comment by dichen-cd** [comment]
NYU_depth 实际占用空间达到了7.3T, 远远超过了428G

**Comment by JesseZhang92** [comment]
NYU_depth 大的原因是由于之前将data2的相关文件夹转移到了这里。由于之前在文件夹里重写了一些数据，因此导致体积比较大。我已经在删除冗余的数据，并且之后不会再里面重写新的数据了。

**Comment by dichen-cd** [comment]
OK，尽量保证数据集干净。
