### ISSUE TITLE
VOC2007

### ISSUE THREAD

**Issue by destinyzs** [DeepInsight-PCALab/Dataset-Catalog-#9]
Name: VOC2007
Path: /data3/VOC2007
Size: 908MB
Home Page: http://host.robots.ox.ac.uk/pascal/VOC/index.html
Keywords: object detection
Miscellaneous: including images,develop kits and  annotations
Li Chengzheng

**Comment by dichen-cd** [comment]
跟 /data3/PASCAL/VOCdevkit/VOC2007 有重叠。

**Comment by destinyzs** [comment]
@DeanChan  那就换成下面的
Name: VOC
Path: /data3/PASCAL/
Size: 4.2GB
Home Page: http://host.robots.ox.ac.uk/pascal/VOC/index.html
Keywords: object detection
Miscellaneous: including images,develop kits and annotations
Li Chengzheng

**Comment by dichen-cd** [comment]
`/data3/PASCAL/` 下包含了 VOC2007, VOC2012以及 VOC0712 三个子集。

**Comment by destinyzs** [comment]
只需要VOC2007和VOC2012
/data3/PASCAL/VOCdevkit/VOC2007、/data3/PASCAL/VOCdevkit/VOC2012
448MB+2.0GB

**Comment by dichen-cd** [comment]
OK. `/data3/PASCAL/VOCdevkit/VOC0712` 将被删除。
